Home work number 1
andrewKarachun0304/TMSHomeWorkAndroid pull request #1
Opened 2020-09-16 11:10 UTC by andrewKarachun0304

Do you approve?

2020-09-16 20:14 UTC, TMSlebedev requested changes

2020-09-16 20:14 UTC, TMSlebedev commented on app/src/main/java/com/andrewKarachun0304/tmshomeworkandroid/MainActivity.kt
> +
Can't see button onClick assignment

2020-09-17 17:46 UTC, Vladislav7776 approved these changes

2020-09-17 17:46 UTC, Vladislav7776 approved these changes

2020-09-18 15:34 UTC, sansaywm approved these changes

2020-09-18 18:11 UTC, Mikhail-Kh approved these changes
Cool!

2020-09-21 12:23 UTC, limitAlltheir approved these changes

2020-09-21 18:54 UTC, TMSlebedev approved these changes
Well done

2020-09-22 06:39 UTC, merged